---
title: "Model Peformance"
auhor: "Casey Breen" 
---

Summary: Generate figures and tables summarizing model performance 

* write out latex tables directly 

```{r}
## libary packages + custom functions 
library(here)
source(here("code", "helpers.R"))
```

## Estimate model performance metrics 

```{r}
## read predictions
predictions_combined <- read_csv(here("out", "combined_predictions_lmics_national_covars_full.csv")) %>%
mutate(predicted = case_when(
    predicted < 0 ~ 0,
    predicted > 1 ~ 1,
    TRUE ~ predicted
  )) %>%
  mutate(observed = case_when(
    observed < 0 ~ 0,
    observed > 1 ~ 1,
    TRUE ~ observed
  ))  %>% 
  mutate(cv_method = case_when(
    grepl("10fold", cv_method) ~ "10-Fold-CV",
    grepl("loco", cv_method) ~ "LOCO-CV",
    TRUE ~ cv_method
  )) %>%
  mutate(outcome_categorical = case_when(
    outcome %in% c(
      "perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio",
      "perc_owns_mobile_telephone_wght_age_15_to_49_men",
      "perc_owns_mobile_telephone_wght_age_15_to_49_wom"
    ) ~ "Mobile",
    outcome %in% c(
      "perc_used_internet_past12months_wght_age_15_to_49_fm_ratio",
      "perc_used_internet_past12months_wght_age_15_to_49_men",
      "perc_used_internet_past12months_wght_age_15_to_49_wom"
    ) ~ "Internet",
  )) 


## read in training and test datasets
gadm1 <- read_csv(here("data", "master_data_file_dec24_with_national.csv"),
  locale = locale(encoding = "ISO-8859-1")) %>%
  janitor::clean_names() %>%
  mutate(pop_all_age_total_dhsyear = pop_all_age_female + pop_all_age_male) %>%
  dplyr::select(country, gid_1, dhsyear, pop_all_age_total_dhsyear, continent) %>%
  filter(!is.na(dhsyear)) %>% 
    filter(!(country == "Bangladesh" & dhsyear == "2014")) %>% 
  filter(!(country == "India" & dhsyear == "2014")) %>% 
  filter(!(country == "Cambodia" & dhsyear == "2014")) %>%
  filter(!(country == "Nepal" & dhsyear == "2016")) %>%
  filter(!(country == "Philippines" & dhsyear == "2017"))

predictions_combined <- predictions_combined %>%
  left_join(gadm1, by = c("gid_1", "country")) 

## estimate model performance metrics
## r2, rmse, mae are fine
## mape and mare are a bit tricky because observed value is sometimes 0
model_performance_metrics <- predictions_combined %>%
  group_by(cv_method, model, outcome, feature_set) %>%
  summarise(
    r = cor(predicted, observed),
    r2 = compute_r2(predicted, observed),
    rmse = compute_rmse(predicted, observed),
    mape = compute_mape(predicted, observed),
    mare = compute_mare(predicted, observed),
    mae = compute_mae(predicted, observed)
  ) %>%
  pivot_longer(
    cols = c(r, r2, rmse, mape, mare, mae),
    names_to = "metric",
    values_to = "value"
  )

## model performance metrics 
model_performance_metrics <- model_performance_metrics %>%
  mutate(outcome_clean = case_when(
    grepl("mobile_telephone_wght_age_15_to_49_fm_ratio", outcome) ~ "Mobile (Ratio)",
    grepl("mobile_telephone_wght_age_15_to_49_men", outcome) ~ "Mobile (Men)",
    grepl("mobile_telephone_wght_age_15_to_49_wom", outcome) ~ "Mobile (Women)",
    grepl("used_internet_past12months_wght_age_15_to_49_fm_ratio", outcome) ~ "Internet (Ratio)",
    grepl("used_internet_past12months_wght_age_15_to_49_men", outcome) ~ "Internet (Men)",
    grepl("used_internet_past12months_wght_age_15_to_49_wom", outcome) ~ "Internet (Women)",
    TRUE ~ outcome
  )) 

## model performance 
model_performance_metrics %>% filter(metric == "r2")

## predictions combined 
predictions_combined <- predictions_combined %>%
  left_join(model_performance_metrics %>% filter(metric == "r2") %>% mutate(r2 = value) %>% select("r2", "metric", "cv_method", "model", "outcome", "feature_set"), by = c("cv_method", "model", "outcome", "feature_set")) %>%
    left_join(model_performance_metrics %>% filter(metric == "r") %>% mutate(r = value) %>% select("r", "metric", "cv_method", "model", "outcome", "feature_set"), by = c("cv_method", "model", "outcome", "feature_set")) %>% 
    left_join(model_performance_metrics %>% filter(metric == "mae") %>% mutate(mae = value) %>% select("mae", "metric", "cv_method", "model", "outcome", "feature_set"), by = c("cv_method", "model", "outcome", "feature_set")) 
```

## observed vs. predicted by outcome 

```{r}
# Plot for "perc_ever_used_internet_wght_age_15_to_49_men"
plot1_observed_predicted <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_wom", "perc_used_internet_past12months_wght_age_15_to_49_wom"),
    feature_set == "fb_and_offline",
    cv_method == "LOCO-CV"
  ) %>%
  ggplot(aes(x = observed, y = predicted, size = pop_all_age_total_dhsyear)) +
  geom_point(alpha = 0.1) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Women") +
  geom_label(
  aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.20,
  y = 0.90,
  size = 3.5) +
  scale_y_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  scale_x_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  facet_wrap(~outcome_categorical, nrow = 2) +
  theme(legend.position = "none")

# Plot for "perc_ever_used_internet_wght_age_15_to_49_"
plot2_observed_predicted <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_men", "perc_used_internet_past12months_wght_age_15_to_49_men"),
    feature_set == "fb_and_offline",
    cv_method == "LOCO-CV"
  ) %>%
  ggplot(aes(x = observed, y = predicted, size = pop_all_age_total_dhsyear)) +
  geom_point(alpha = 0.1) +
    scale_y_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
    scale_x_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Men") +
   geom_label(
  aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.20,
  y = 0.90,
  size = 3.5) +
  facet_wrap(~outcome_categorical, nrow = 2) +
  theme(legend.position = "none")


# Plot for "perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio"
plot3_observed_predicted <- predictions_combined %>%
  # mutate(r2 = paste0("italic(R)^2~`=`~", round(r2, 2))) %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio", "perc_used_internet_past12months_wght_age_15_to_49_fm_ratio"),
    feature_set == "fb_and_offline",
    cv_method == "LOCO-CV"
  ) %>%
  ggplot(aes(x = observed, y = predicted, size = pop_all_age_total_dhsyear)) +
  geom_point(alpha = 0.1) +
  ylim(0, 1.5) +
  xlim(0, 1.5) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Gender Gap", size = "Population Size") +
     geom_label(aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.25,
  y = 1.2,
  size = 3.5) +
  facet_wrap(~outcome_categorical, nrow = 2) +
  theme(legend.position = "none") +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1)))

# Combine plots using cowplot's plot_grid
combined_plot_observed_predicted <- plot_grid(plot1_observed_predicted, plot2_observed_predicted, plot3_observed_predicted, ncol = 3, labels = "AUTO")

# Extract the legend from plot3_internet12m (or from whichever plot you prefer)
legend <- ggpubr::get_legend(
  plot3_observed_predicted + theme(legend.position = "bottom", legend.direction = "horizontal")
)

# Combine the combined_plots with the extracted legend and place it at the bottom
combined_plot_observed_predicted_legend <- plot_grid(combined_plot_observed_predicted, legend, ncol = 1, rel_heights = c(1, .1))

ggsave(plot = combined_plot_observed_predicted_legend, here("figures", "observed_predicted_loco_complete_fig.png"), width = 10, height = 6)
```

```{r}
# Plot for "perc_ever_used_internet_wght_age_15_to_49_men"
plot1_combined <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_wom", "perc_used_internet_past12months_wght_age_15_to_49_wom"),
    feature_set == "fb_and_offline") %>% 
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(aes(size = pop_all_age_total_dhsyear), alpha = 0.1) +
  # geom_smooth() +
    scale_y_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
    scale_x_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Women") +
  geom_label(
  aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.20,
  y = 0.90,
  size = 3.5) +
  facet_grid(rows = vars(outcome_categorical), cols = vars(cv_method)) +
  theme(legend.position = "none") 


# Plot for "perc_ever_used_internet_wght_age_15_to_49_wom"
plot2_combined <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_men", "perc_used_internet_past12months_wght_age_15_to_49_men"),
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(aes(size = pop_all_age_total_dhsyear), alpha = 0.1) +
  # geom_smooth() +
    scale_y_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
    scale_x_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Men") +
  geom_label(
  aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.20,
  y = 0.90,
  size = 3.5) +
  facet_grid(rows = vars(outcome_categorical), cols = vars(cv_method)) +
  theme(legend.position = "none") 


plot3_combined <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio", "perc_used_internet_past12months_wght_age_15_to_49_fm_ratio"),
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(aes(size = pop_all_age_total_dhsyear), alpha = 0.1) +
  ylim(0, 1.5) +
  xlim(0, 1.5) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Gender Gap", size = "Population Size") +
  geom_label(
  aes(
    label = paste0(
  "R\u00B2 = ", round(r2, 2), "\n",
  "r = ", round(r, 2), "\n",
  "MAE = ", round(mae, 2))), 
  x = 0.20,
  y = 1.20,
  size = 3.5) +
  facet_grid(rows = vars(outcome_categorical), cols = vars(cv_method)) +
  theme(legend.position = "none") +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000),
    labels = c("300k", "1m", "3m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) 


# Extract the legend from plot3_internet12m (or from whichever plot you prefer)
legend <- cowplot::get_legend(
  plot3_combined + theme(legend.position = "bottom", legend.direction = "horizontal")
)

# Combine the plots without legends
plot_combined_observed_predicted <- plot_grid(plot1_combined, plot2_combined, plot3_combined, ncol = 1, labels = "AUTO", align = "v")

# Combine the combined_plots with the extracted legend and place it at the bottom
plot_combined_observed_predicted_legend <- plot_grid(plot_combined_observed_predicted, legend, ncol = 1, rel_heights = c(1, .1))

ggsave(plot = plot_combined_observed_predicted_legend, here("figures" ,"plot_combined_observed_predicted.png"), width = 6, height = 18)
```



```{r}
## observed predicted used internet
observed_predicted_plot_country_mobile_wom <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    feature_set == "fb_and_offline",
    outcome == "perc_owns_mobile_telephone_wght_age_15_to_49_wom"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(alpha = 0.3, aes(size = pop_all_age_total_dhsyear)) +
  stat_cor(aes(x = observed, y = predicted, label = paste0("italic(r)~`=`~", ..r..))) + # Adjusted stat_cor
  labs(
    title = "Own mobile, women",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1) +
  ylim(0, 1) +
    facet_wrap(~country) +
  geom_abline(slope = 1, linetype = "dashed") +
  # facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom")


## observed predicted used internet
observed_predicted_plot_country_mobile_men <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    outcome == "perc_owns_mobile_telephone_wght_age_15_to_49_men",
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(aes(size = pop_all_age_total_dhsyear), alpha = 0.3) +
  # geom_smooth() +
  stat_cor(aes(label =  paste0("italic(r)~`=`~", ..r..))) +
  labs(
    title = "Own mobile, men",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom")

## observed predicted used internet
observed_predicted_plot_country_mobile_fm_ratio <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    outcome == "perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio",
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(alpha = 0.3, aes(size = pop_all_age_total_dhsyear)) +
  # geom_smooth() +
  stat_cor(aes(label =  paste0("italic(r)~`=`~", ..r..))) +
  labs(
    title = "Own mobile, gender gap",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1.5) +
  ylim(0, 1.5) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom")  +
  theme(axis.text.x = element_text(angle = -90))

## save plots
ggsave(plot = observed_predicted_plot_country_mobile_wom, filename = here("figures", "observed_predicted_plot_country_mobile_wom.png"), width = 9, height = 7.5)
ggsave(plot = observed_predicted_plot_country_mobile_men, filename = here("figures", "observed_predicted_plot_country_mobile_men.png"), width = 9, height = 7.5)
ggsave(plot = observed_predicted_plot_country_mobile_fm_ratio, filename = here("figures", "observed_predicted_plot_country_mobile_fm_ratio.png"), width = 10.5, height = 8.2)
```


```{r}
## observed predicted used internet
observed_predicted_plot_country_internet_wom <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    feature_set == "fb_and_offline",
    outcome == "perc_used_internet_past12months_wght_age_15_to_49_wom"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(alpha = 0.3, aes(size = pop_all_age_total_dhsyear)) +
  # geom_smooth() +
  stat_cor(aes(label = paste0("italic(r)~`=`~", ..r..))) +
  labs(
    title = "Internet, women",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom")

## observed predicted used internet
observed_predicted_plot_country_internet_men <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    outcome == "perc_used_internet_past12months_wght_age_15_to_49_men",
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(alpha = 0.3, aes(size = pop_all_age_total_dhsyear)) +
  stat_cor(aes(label = paste0("italic(r)~`=`~", ..r..))) +
  labs(
    title = "Internet, men",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1) +
  ylim(0, 1) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom")

## observed predicted used internet
observed_predicted_plot_country_internet_fm_ratio <- predictions_combined %>%
  filter(
    model == "superlearner",
    cv_method == "LOCO-CV",
    outcome == "perc_used_internet_past12months_wght_age_15_to_49_fm_ratio",
    feature_set == "fb_and_offline"
  ) %>%
  ggplot(aes(x = observed, y = predicted)) +
  geom_point(alpha = 0.3, aes(size = pop_all_age_total_dhsyear)) +
  # geom_smooth() +
  stat_cor(aes(label = paste0("italic(r)~`=`~", ..r..))) +
  labs(
    title = "Internet, gender gap",
    x = "Observed",
    y = "Predicted",
    size = "Population Size"
  ) +
  theme_cowplot() +
  xlim(0, 1.5) +
  ylim(0, 1.5) +
  geom_abline(slope = 1, linetype = "dashed") +
  facet_wrap(~country) +
  scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) +
  theme(legend.position = "bottom") + 
  theme(axis.text.x = element_text(angle = -90))

## save plots
ggsave(plot = observed_predicted_plot_country_internet_wom, filename = here("figures", "observed_predicted_plot_country_internet_wom.png"), width = 9, height = 7.5)
ggsave(plot = observed_predicted_plot_country_internet_men, filename = here("figures", "observed_predicted_plot_country_internet_men.png"), width = 9, height = 7.5)
ggsave(plot = observed_predicted_plot_country_internet_fm_ratio, filename = here("figures", "observed_predicted_plot_country_internet_fm_ratio.png"), width = 9, height = 7.5)
```


```{r}
country_r2_df <- predictions_combined %>%
  group_by(cv_method, model, outcome, feature_set, country) %>%
    filter(
    model == "superlearner",
    feature_set == "fb_and_offline"
  ) %>%
  summarise(
    r2 = compute_r2(predicted, observed),
    r2_alt = calculate_r_squared(predicted, observed),
    cor = cor(predicted, observed),
    mae = mean(abs(observed - predicted)),
    mse = mean(sqrt((observed - predicted)^2))
  )

country_level_mae <- country_r2_df %>%
  filter(outcome == "perc_used_internet_past12months_wght_age_15_to_49_wom") %>%
  ggplot(aes(x = mae)) +
  geom_density(aes(color = cv_method, fill = cv_method, y = after_stat(count) / sum(after_stat(count))), alpha = 0.2) +
  labs(x = "Mean absolute error", y = "Proportion") +
  theme_cowplot() +
 # xlim(0, 1) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  scale_fill_manual(values = cud[1:2]) + 
  scale_color_manual(values = cud[1:2]) 

country_level_corr <- country_r2_df %>%
  filter(outcome == "perc_used_internet_past12months_wght_age_15_to_49_wom") %>%
  ggplot(aes(x = cor)) +
  geom_density(aes(color = cv_method, fill = cv_method, y = after_stat(count) / sum(after_stat(count))), alpha = 0.2) +
  labs(x = "Correlation", y = "Proportion") +
  theme_cowplot() +
 # xlim(0, 1) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  scale_fill_manual(values = cud[1:2]) + 
  scale_color_manual(values = cud[1:2]) + 
  xlim(0, 1)

## save plots as rds bc we'll need to use them later in a multi-panel plot 
write_rds(country_level_mae, file = here("figures", "country_level_mae.rds"))
write_rds(country_level_corr, file = here("figures", "country_level_corr.rds"))

```

```{r}
# Combine `outcome_categorical` and `dhsyear` into a single facet variable
predictions_combined <- predictions_combined %>%
  mutate(facet_variable = paste(outcome_categorical, dhsyear, sep = " - "))

# Compute MAE and correlation
predictions_combined_summary <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_used_internet_past12months_wght_age_15_to_49_wom"),
    feature_set == "fb_and_offline",
    cv_method == "LOCO-CV"
  ) %>%
  group_by(facet_variable) %>%
  summarise(
    mae = mean(abs(predicted - observed)),
    r = cor(observed, predicted)
  )

# Plot
loco_by_year_fig <- predictions_combined %>%
  filter(
    model == "superlearner",
    outcome %in% c("perc_used_internet_past12months_wght_age_15_to_49_wom"),
    feature_set == "fb_and_offline",
    cv_method == "LOCO-CV"
  ) %>%
  ggplot(aes(x = observed, y = predicted, size = pop_all_age_total_dhsyear)) +
  geom_point(alpha = 0.2) +
  geom_abline(slope = 1, linetype = "dashed", color = "grey") +
  theme_cowplot() +
  labs(title = "Women",
       size = "Population size") +
  scale_y_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  scale_x_continuous(limits = c(0, 1.1), labels = scales::label_percent()) +
  facet_wrap(~facet_variable, nrow = 2) +
  theme(legend.position = "bottom") +
  geom_label(
    data = predictions_combined_summary,
    aes(
      x = 0.3, 
      y = 0.9,
      label = paste("atop(italic(r) == ", round(r, 2), ", italic(MAE) == ", round(mae, 2), ")")
    ),
    parse = TRUE,
    inherit.aes = FALSE,
    size = 3
  ) + 
   scale_size_continuous(
    breaks = c(300000, 1000000, 3000000, 10000000),
    labels = c("300k", "1m", "3m", "10m")
  ) +
  guides(size = guide_legend(override.aes = list(alpha = 1))) 


ggsave(plot = loco_by_year_fig, filename = here("figures", "loco_by_year_fig.png"), width = 9, height = 5)

```








