---
title: "Additional appendix tables"
author: Casey Breen
---

Summary: This script reads in DHS data and creates a table

```{r}
## libary packages + custom functions 
library(here)
source(here("code", "helpers.R"))
```


```{r}
master_file <- read_csv(here("data", "master_data_file_dec24_with_national.csv")) 
```



```{r}
master_file_full <- read_csv(here("data", "master_data_file_dec24_with_national.csv"), 
                       locale = locale(encoding = "ISO-8859-1"),
                       show_col_types = FALSE) %>%
  janitor::clean_names() %>% 
  mutate(continent = case_when(continent == "Africa" ~ 1,
                               TRUE ~ 0)) %>% 
  filter(!(country == "Bangladesh" & dhsyear == "2014")) %>% 
  filter(!(country == "India" & dhsyear == "2014")) %>% 
  filter(!(country == "Cambodia" & dhsyear == "2014")) %>%
  filter(!(country == "Nepal" & dhsyear == "2016")) %>%
  filter(!(country == "Philippines" & dhsyear == "2017")) %>%
  mutate(pop_all_age_total = pop_all_age_female + pop_all_age_male) %>%
  filter(!is.na(fb_pntr_18p_female)) %>% 
  mutate(
    nl_mean_zscore,
    pop_density,
    pop_all_age_female,
    pop_all_age_male,
    subnational_gdi,
    subnational_hdi_males,
    subnational_hdi_females,
    educational_index_females,
    educational_index_males,
    income_index_females,
    income_index_males,
    internet_speed,
    continent ,
    hdi,
    gdi)
```


```{r}
## columns 
master_file_select <- master_file %>% 
  dplyr::select(gid_0, gid_1, country, dhs_vars, off_feats, fb_feats)

result_list <- list()
i = 1
for (col in colnames(master_file_select %>% dplyr::select(-country)) ) {
  
  total_country <- master_file_select %>% 
    filter(!is.na(!!sym(col))) %>% 
    distinct(country) %>% 
    count() %>% 
    pull()
  
  total_subnational <- master_file_select %>% 
    filter(!is.na(!!sym(col))) %>% 
    distinct(gid_1) %>% 
    count() %>% 
    pull()

  
  df <- tibble(col, total_country, total_subnational) #%>% 
   # bind_cols(total_subnational_metrics)
  
  result_list[[i]] <- df 
  
  i = i + 1
}

table_variables <- bind_rows(result_list) 

variable_table <- table_variables %>% 
  mutate(across(where(is.numeric), ~round(., 1)))



print(xtable(variable_table, digits = 0), include.rownames=FALSE, file = here("figures", "variable_table.tex"))
```