---
title: "Predicted error"
author: Casey Breen
---

## Summary 

Compare predicted error vs. real LSMS error 

```{r}
## libary packages + custom functions 
library(here)
source(here("code", "helpers.R"))
```

```{r}
## read in data 
lsms_estimates <- read_csv(here("data", "lsms_ground_truth.csv"))

## Read in data 
ground_truth_lsms <- read_csv(here("data", "subnational_master_file_for_repetitive_measurement.csv")) %>% 
  filter(survey_type == "lsms")

## read in predictions 
predictions <- read_csv(here("out", "predictions_with_uncertainty.csv"))

## read in ground truth 
gadm1 <- read_csv(here("data", "subnational_ground_truth_sep17_2024.csv"), locale = locale(encoding = "ISO-8859-1")) %>% 
  mutate(observed = case_when(
    outcome %in% c("internet_fm_ratio", "mobile_fm_ratio") ~ observed,
    TRUE ~ observed / 100))
```




```{r}
lsms_estimates_long <- lsms_estimates %>% 
    # filter(!gid_1 %in% gadm1$gid_1) %>% 
  filter(!(iso3 == "NER" & survey_year == 2021)) %>% 
 filter(internet_n_sample_f > 1000) %>% 
  select(iso3, gid_1, survey_year, internet_women = internet_f_weighted, internet_men =  internet_m_weighted, mobile_women = mobile_f_weighted, mobile_men = mobile_m_weighted) %>% 
  mutate(mobile_fm_ratio = mobile_women/mobile_men) %>% 
  mutate(internet_fm_ratio = internet_women/internet_men) %>% 
  pivot_longer(-c(gid_1, iso3, survey_year)) %>% 
  rename(lsms_estimate = value, outcome = name)

lsms_estimates_long <- lsms_estimates_long %>% 
  filter(!(iso3 == "NGA" & outcome %in% c("mobile_women", "mobile_men", "mobile_fm_ratio")))
```


```{r}
# Joining Data
lsms_data <- predictions %>% 
  select(gid_1, predicted, predicted_error, outcome, year) %>% 
  inner_join(lsms_estimates_long, by = c("year" = "survey_year", "gid_1", "outcome")) %>% 
  filter(!is.na(lsms_estimate) & !is.na(predicted)) #%>%  filter(iso3 != "NER")

# Calculate R-squared and correlation (r) by outcome
r_squared_results <- lsms_data %>%
  group_by(outcome) %>%
  summarize(
    r = cor(predicted, lsms_estimate, use = "complete.obs"),  # Calculate correlation
    r2 = compute_r2(predicted, lsms_estimate),  # Calculate R-squared
    mae = mean(abs(predicted - lsms_estimate)), 
    .groups = "drop"
  )

lsms_data <-  lsms_data %>% 
   mutate(outcome_clean = case_when(
    grepl("mobile_fm_ratio", outcome) ~ "Mobile (Ratio)",
    grepl("mobile_men", outcome) ~ "Mobile (Men)",
    grepl("mobile_women", outcome) ~ "Mobile (Women)",
    grepl("internet_fm_ratio", outcome) ~ "Internet (Ratio)",
    grepl("internet_men", outcome) ~ "Internet (Men)",
    grepl("internet_women", outcome) ~ "Internet (Women)",
    TRUE ~ outcome
  )) %>% mutate(outcome_clean = factor(outcome_clean, 
                                levels = c("Internet (Women)", "Internet (Men)", "Internet (Ratio)",
                                           "Mobile (Women)", "Mobile (Men)", "Mobile (Ratio)")))

lsms_data %>% 
  mutate(error = predicted - lsms_estimate) %>% 
  count(abs(error) > predicted_error)

lsms_data %>% 
  mutate(error = predicted - lsms_estimate) %>% 
  summarize(error = mean(abs(error)), predicted_error = mean(predicted_error)) 

lsms_error_plot <-  lsms_data %>% 
  group_by(outcome_clean) %>% 
  mutate(error = predicted - lsms_estimate) %>% 
  summarize(`Observed error (LSMS)` = mean(abs(error)), `Predicted error` = mean(predicted_error)) %>% 
  pivot_longer(-outcome_clean) %>% 
  ggplot(aes(x = outcome_clean, y = value, fill = name)) + 
  geom_col(position = "dodge", alpha = 0.5, color = "black") + 
  scale_fill_viridis_d() + 
  theme_cowplot() + 
  theme(legend.position = "bottom") + 
  labs(x = "",
       y = "Mean Error",
       fill = "")

## lsms error plots 
ggsave(plot = lsms_error_plot, filename = here("figures", "lsms_error_plot.png"), width = 10, height = 5)
```







