---
title: "MICS Surveys"
author: Casey Breen
---

Summary: Calculate subnational estimates for MICS surveys. 


```{r}
## libary packages + custom functions 
library(here)
source(here("code", "helpers.R"))

## read in predictions
predictions <- fread(here("out", "predictions_with_uncertainty.csv")) %>% 
  filter(year != 2024)

## MICS Estimates 
data <- read_csv('/Users/caseybreen/Library/CloudStorage/Dropbox-NuffieldCollege/Casey Breen/dgg_research/subnational/analysis_files/supplymentary_files/outcome/master_file_for_repetitive_measurement.csv') 

## Recode incorrect year for Afghanistan 
data <- data %>% 
  mutate(year = case_when(year == 1401 ~ 2022, TRUE ~ year))

## Fix data 
data %>% 
  filter(survey_type == "mics") %>% 
  count(gid_0, year)
```


```{r}
## Exclude some some surveys that are duplicated 
data_dhs_mics <- data %>% 
  filter(mobile_n_sample_f > 150 & mobile_n_sample_m > 150) %>% 
  filter(internet_n_sample_f > 150 & internet_n_sample_m > 150) %>% 
  filter(survey_type == "mics")

## MICS estimates long 
estimates_long <- data_dhs_mics %>% 
  select(gid_0, gid_1, year, survey_type, 
         internet_women = perc_used_internet_past12months_wght_age_15_to_49_wom, 
         internet_men =  perc_used_internet_past12months_wght_age_15_to_49_men,
         mobile_women =  perc_owns_mobile_telephone_wght_age_15_to_49_wom,
         mobile_men = perc_owns_mobile_telephone_wght_age_15_to_49_men,
         mobile_fm_ratio = perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio,
         internet_fm_ratio = perc_used_internet_past12months_wght_age_15_to_49_fm_ratio) %>% 
  pivot_longer(-c(gid_1, gid_0, year, survey_type)) %>% 
  rename(observed = value, outcome = name) 

## Estimates long 
estimates_long <-  estimates_long %>%
  mutate(observed = case_when(observed > 1 ~ 1, TRUE ~ observed))
```

```{r}
## Estimates long 
estimates_long %>% 
  left_join(predictions)

## prepare df 
subnational_predictions_comparison_df <- estimates_long %>% 
  left_join(predictions, by = join_by(gid_0, gid_1, year, outcome)) %>% 
  distinct() %>% 
   mutate(outcome_clean = case_when(
    grepl("mobile_fm_ratio", outcome) ~ "Mobile (Ratio)",
    grepl("mobile_men", outcome) ~ "Mobile (Men)",
    grepl("mobile_women", outcome) ~ "Mobile (Women)",
    grepl("internet_fm_ratio", outcome) ~ "Internet (Ratio)",
    grepl("internet_men", outcome) ~ "Internet (Men)",
    grepl("internet_women", outcome) ~ "Internet (Women)",
    TRUE ~ outcome
  ))

# Define the order of the levels explicitly
subnational_predictions_comparison_df <- subnational_predictions_comparison_df %>% 
  mutate(outcome_clean = factor(outcome_clean, 
                                levels = c("Internet (Women)", "Internet (Men)", "Internet (Ratio)",
                                           "Mobile (Women)", "Mobile (Men)", "Mobile (Ratio)")))

# Calculate R-squared and correlation (r) by outcome
r_squared_results <- subnational_predictions_comparison_df %>%
  filter(!is.na(observed)) %>% 
    filter(!is.na(predicted)) %>% 
  group_by(outcome_clean) %>%
  summarize(
    r = cor(observed, predicted, use = "complete.obs"),  # Calculate correlation
    r2 = compute_r2(observed, predicted),  # Calculate R-squared
    mae = mean(abs(observed - predicted)), 
    .groups = "drop"
  )

mics_comparison_fig <- subnational_predictions_comparison_df %>% 
  left_join(r_squared_results) %>% 
  ggplot(aes(x = observed, y = predicted, color = year)) + 
  geom_point(size = 2, alpha = 0.85) +
  geom_abline(color = "grey60", linetype = "dashed") +
  xlim(0, 1) + 
  ylim(0, 1) + 
  labs(
    x = "Ground Truth, MICS (Admin-1 Level)",
    y = "Predicted (Admin-1 Level)",
    color = "MICS Survey Year"
  ) +
  geom_label(
    aes(
      label = paste0("atop(italic(r)==", round(r, 2), ",~italic(MAE)==", round(mae, 2), ")")
    ),
    parse = TRUE,
    x = 0.20,
    y = 0.9,
    size = 3.2,
    inherit.aes = FALSE
  ) +
  facet_wrap(~ outcome_clean, ncol = 3) +
  theme_cowplot() +
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold", color = "black"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9", color = NA),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    legend.position = "bottom",
    legend.justification = "center",  # centers the whole legend box
    legend.title = element_text(size = 13, hjust = 0.5, vjust = 1, margin = margin(b = 4)),
    legend.text = element_text(size = 11)
  ) +
  guides(
    color = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      barwidth = unit(10, "cm"),
      barheight = unit(0.5, "cm")))

mics_comparison_fig

ggsave(plot = mics_comparison_fig, filename = here("figures", "mics_comparison_subnational.png"), height = 7, width = 10)

```

