---
title: "Validation of trends"
author: Casey Breen
---

Summary: Validate trends estimates

```{r}
## libary packages + custom functions 
library(here)
source(here("code", "helpers.R"))
```

```{r}
## read in data 
lsms_estimates <- read_csv(here("data", "lsms_ground_truth.csv")) %>% 
  janitor::clean_names()

predictions <- read_csv(here("out", "predictions_with_uncertainty.csv")) %>% 
  mutate(predicted = case_when(
    predicted > 1 ~ 1,
    TRUE ~ predicted
  ))

gadm1 <- read_csv(here("data", "subnational_ground_truth_sep17_2024.csv"), locale = locale(encoding = "ISO-8859-1")) %>% 
  mutate(observed = case_when(
    outcome %in% c("internet_fm_ratio", "mobile_fm_ratio") ~ observed,
    TRUE ~ observed / 100))

predictions <- read_csv(here("out", "predictions_with_uncertainty.csv")) %>% 
  mutate(predicted = case_when(
    predicted > 1 ~ 1,
    TRUE ~ predicted
  ))

## data 
data <- read_csv('/Users/caseybreen/Library/CloudStorage/Dropbox-NuffieldCollege/Casey Breen/dgg_research/subnational/analysis_files/supplymentary_files/outcome/master_file_for_repetitive_measurement.csv')

## mics 
mics <- read_csv("/Users/caseybreen/Library/CloudStorage/Dropbox-NuffieldCollege/Casey Breen/dgg_research/subnational/analysis_files/supplymentary_files/outcome/mics.csv")

# Example: Get GADM1 names for Nigeria
gadm1_map <- read_sf(here("data", "gadm_410-levels.gpkg"), layer = "ADM_1")

gadm1_map_nigeria <- gadm1_map %>% 
  filter(COUNTRY == "Nigeria")
```

```{r}
## Exclude some some surveys that are duplicated 
data_dhs_mics <- data %>% 
 # filter(survey_type %in% c("dhs", "mics")) %>% 
  filter(mobile_n_sample_f > 100 | survey_type %in% c("dhs")) %>% 
  filter(survey_type != "lsms") %>% 
   filter(!(gid_0 == "NGA" & survey_type == "lsms" & year == 2018)) %>% 
   filter(!(gid_0 == "BFA" & survey_type == "lsms" & year == 2021))

## DHS MICS data 
estimates_long <- data_dhs_mics %>% 
  select(gid_0, gid_1, year, survey_type, 
         internet_women = perc_used_internet_past12months_wght_age_15_to_49_wom, 
         internet_men =  perc_used_internet_past12months_wght_age_15_to_49_men,
         mobile_women =  perc_owns_mobile_telephone_wght_age_15_to_49_wom,
         mobile_men = perc_owns_mobile_telephone_wght_age_15_to_49_men,
         mobile_fm_ratio = perc_owns_mobile_telephone_wght_age_15_to_49_fm_ratio,
         internet_fm_ratio = perc_used_internet_past12months_wght_age_15_to_49_fm_ratio) %>% 
  pivot_longer(-c(gid_1, gid_0, year, survey_type)) %>% 
  rename(estimate = value, outcome = name) 

## estimates long 
estimates_long <-  estimates_long %>%
  mutate(estimate = case_when(estimate > 1 ~ 1, TRUE ~ estimate))
```

```{r}
multi_survey <- estimates_long %>% 
  count(gid_0, year, survey_type) %>% 
  group_by(gid_0) %>% 
  filter(n() > 2) %>% 
  arrange(desc(gid_0)) %>% 
  select(gid_0, year, survey_type) %>% 
  knitr::kable()
```


```{r}
df_change <- estimates_long %>%
  group_by(gid_0, gid_1, outcome) %>%
    filter(n_distinct(year) > 1) %>%  # only keep groups with more than one year
  arrange(year) %>%
  summarize(
    year_start = dplyr::first(year),
    year_end = dplyr::last(year),
    estimate_start = dplyr::first(estimate),
    estimate_end = dplyr::last(estimate),
    change = estimate_end - estimate_start,
    .groups = "drop"
  )

pred_change <- predictions %>%
  inner_join(df_change %>% select(gid_1, outcome, year_start, year_end),
             by = c("gid_1", "outcome")) %>%
  filter(year %in% c(year_start, year_end)) %>%
  select(gid_1, outcome, year, predicted, year_start, year_end)

pred_change_wide <- pred_change %>%
  pivot_wider(names_from = year, values_from = predicted, names_prefix = "year_") %>%
  rowwise() %>%
  mutate(predicted_change = cur_data()[[paste0("year_", year_end)]] - 
                          cur_data()[[paste0("year_", year_start)]]) %>%
  ungroup() %>%
  select(gid_1, outcome, year_start, year_end, predicted_change)


pred_change_wide

change_df <- df_change %>% 
  left_join(pred_change_wide)
```

```{r}
model_performance_metrics <- change_df %>%
  filter(!is.na(predicted_change) & !is.na(change)) %>% 
  group_by(outcome) %>%
  summarise(
    r = cor(predicted_change, change),
    r2 = compute_r2(predicted_change, change),
    rmse = compute_rmse(predicted_change, change),
    mape = compute_mape(predicted_change, change),
    mare = compute_mare(predicted_change, change),
    mae = compute_mae(predicted_change, change)
  )

change_df_metrics <- change_df %>% 
  left_join(model_performance_metrics)

change_df_metrics <-  change_df_metrics %>% 
   mutate(outcome_clean = case_when(
    grepl("mobile_fm_ratio", outcome) ~ "Mobile (Ratio)",
    grepl("mobile_men", outcome) ~ "Mobile (Men)",
    grepl("mobile_women", outcome) ~ "Mobile (Women)",
    grepl("internet_fm_ratio", outcome) ~ "Internet (Ratio)",
    grepl("internet_men", outcome) ~ "Internet (Men)",
    grepl("internet_women", outcome) ~ "Internet (Women)",
    TRUE ~ outcome
  )) %>% mutate(outcome_clean = factor(outcome_clean, 
                                levels = c("Internet (Women)", "Internet (Men)", "Internet (Ratio)",
                                           "Mobile (Women)", "Mobile (Men)", "Mobile (Ratio)")))


time_series_plot <- change_df_metrics %>% 
  mutate(diff = year_start - year_end) %>% 
  ggplot(aes(x = change, y = predicted_change)) + 
  geom_point(alpha = 0.2,size = 2,) + 
  facet_wrap(~outcome_clean) + 
  geom_label(
    aes(label = paste("atop(italic(r) == ", round(r, 2), ", italic(MAE) == ", round(mae, 2), ")")),
    x = -0.2,  # Adjusted position for better visibility
    y = 0.7, 
    size = 3.5,
    parse = TRUE,
    inherit.aes = FALSE
  ) +
  geom_abline(color = "darkgrey", slope = 1, linetype = "dashed") + 
  theme_cowplot() + 
  xlim(-.4, 1) + 
  ylim(-.4, 1)  + 
  labs(x = "Observed Change (Admin-1)",
       y = "Predicted Change (Admin-1)") + 
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold", color = "black"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9", color = NA),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    legend.position = "bottom",
    legend.justification = "center",  # centers the whole legend box
    legend.title = element_text(size = 13, hjust = 0.5, vjust = 1, margin = margin(b = 4)),
    legend.text = element_text(size = 11)
  ) +
  guides(
    color = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      barwidth = unit(10, "cm"),
      barheight = unit(0.5, "cm")))

ggsave(plot = time_series_plot, filename = here("figures", "time_series_plot_scatter.png"), width = 10, height = 7, bg = "white")
```

```{r}
## time series plot 
time_series_plot_scatter_country <- change_df_metrics %>% 
  filter(!gid_0 %in% c("PHL")) %>% 
  ggplot(aes(x = change, y = predicted_change)) + 
  geom_point() + 
  facet_wrap(~outcome) + 
  geom_abline(color = "darkgrey", slope = 1, linetype = "dashed") + 
  theme_cowplot() + 
  xlim(-.5, 0.5) + 
  ylim(-.5, .5) + 
  facet_grid(gid_0 ~ outcome_clean, scales = "free") + 
  labs(x = "Observed Change (Admin-1)",
       y = "Predicted Change (Admin-1)") + 
  theme(
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 10, face = "bold", color = "black"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9", color = NA),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(.5, "lines"),
    aspect.ratio = .9,
    legend.position = "bottom",
    legend.justification = "center",
    legend.title = element_text(size = 13, hjust = 0.5, vjust = 1, margin = margin(b = 4)),
    legend.text = element_text(size = 11),
    axis.text.x = element_text(angle = 45, hjust = 1)  # <- rotation added
  )

## plot figure 
ggsave(plot = time_series_plot_scatter_country, filename = here("figures", "time_series_plot_scatter_country.png"), width = 12, height = 18, bg = "white")

```

```{r}
## create combined dataframe 
df_nigeria <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="NGA", outcome=="mobile_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) %>% 
  filter(!(survey_type == "lsms" & year == 2018)) 


## Join on state names 
df_nigeria <- df_nigeria %>% 
  left_join(gadm1_map_nigeria %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_nigeria <- df_nigeria %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS (2018)",
      survey_type == "MICS" ~ "MICS (2021)",
      survey_type == "LSMS" ~ "LSMS (2023)",
      TRUE ~ "Predicted"
    ),
    source_type = factor(source_type, levels = c("DHS (2018)", "MICS (2021)", "LSMS (2023)", "Predicted"))
  )

# Recode survey types for legend
df_nigeria <- df_nigeria %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS (2018)",
      survey_type == "MICS" ~ "MICS (2021)",
      survey_type == "LSMS" ~ "LSMS (2023)",
      TRUE ~ "Predicted"
    ),
    source_type = factor(source_type, levels = c("DHS (2018)", "MICS (2021)", "LSMS (2023)", "Predicted"))
  )

nigeria_plot <- df_nigeria %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_nigeria, source_type == "Predicted"),
    aes(y = predicted, group = gid_1, color = source_type),
    linewidth = 1.5
  ) +
  geom_point(
    data = filter(df_nigeria, source_type != "Predicted"),
    aes(y = estimate, color = source_type, shape = source_type),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS (2018)" = "darkorange",
      "MICS (2021)" = "red",
      "LSMS (2023)" = "darkred",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS (2018)" = 16,
      "MICS (2021)" = 15,
      "LSMS (2023)" = 17
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Internet Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = nigeria_plot, filename = here("figures", "nigeria_time_series_validation.png"), width = 12, heigh = 12) 
```



```{r}
## create combined dataframe 
df_nigeria <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="NGA", outcome=="mobile_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) %>% 
  filter(!(survey_type == "lsms" & year == 2018)) 


## Join on state names 
df_nigeria <- df_nigeria %>% 
  left_join(gadm1_map_nigeria %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_nigeria <- df_nigeria %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS (2018)",
      survey_type == "MICS" ~ "MICS (2021)",
      survey_type == "LSMS" ~ "LSMS (2023)",
      TRUE ~ "Predicted"
    ),
    source_type = factor(source_type, levels = c("DHS (2018)", "MICS (2021)", "LSMS (2023)", "Predicted"))
  )

# Recode survey types for legend
df_nigeria <- df_nigeria %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS (2018)",
      survey_type == "MICS" ~ "MICS (2021)",
      survey_type == "LSMS" ~ "LSMS (2023)",
      TRUE ~ "Predicted"
    ),
    source_type = factor(source_type, levels = c("DHS (2018)", "MICS (2021)", "LSMS (2023)", "Predicted"))
  )

nigeria_plot <- df_nigeria %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_nigeria, source_type == "Predicted"),
    aes(y = predicted, group = gid_1, color = source_type),
    linewidth = 1.5
  ) +
  geom_point(
    data = filter(df_nigeria, source_type != "Predicted"),
    aes(y = estimate, color = source_type, shape = source_type),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS (2018)" = "darkorange",
      "MICS (2021)" = "red",
      "LSMS (2023)" = "darkred",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS (2018)" = 16,
      "MICS (2021)" = 15,
      "LSMS (2023)" = 17
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Mobile Adoption (Women)",
    title = "Togo, Mobile Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = nigeria_plot, filename = here("figures", "nigeria_time_series_validation_mobile.png"), width = 12, heigh = 12) 
```



```{r}
## create combined dataframe 
df_togo <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="TGO", outcome=="internet_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) 

## Join on state names 
df_togo <- df_togo %>% 
  left_join(gadm1_map %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_togo <- df_togo %>%
  mutate(
    source_type = case_when(
      survey_type == "LSMS" ~ "LSMS",
      TRUE ~ "Predicted"
    ))

togo_plot <- df_togo %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_togo, source_type == "Predicted"),
    aes(y = predicted, group = gid_1, color = source_type),
    linewidth = 1.5
  ) +
  geom_point(
    data = filter(df_togo, source_type != "Predicted"),
    aes(y = estimate, color = source_type, shape = source_type),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS" = "darkorange",
      "MICS" = "red",
      "LSMS" = "darkred",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS" = 16,
      "MICS" = 15,
      "LSMS" = 17
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Internet Adoption (Women)",
    title = "Togo, Internet Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = togo_plot, filename = here("figures", "togo_time_series_validation_internet.png"), width = 12, heigh = 12) 
```

```{r}
## create combined dataframe 
df_togo <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="TGO", outcome=="mobile_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) 

## Join on state names 
df_togo <- df_togo %>% 
  left_join(gadm1_map %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_togo <- df_togo %>%
  mutate(
    source_type = case_when(
      survey_type == "LSMS" ~ "LSMS",
      TRUE ~ "Predicted"
    ))

togo_plot <- df_togo %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_togo, source_type == "Predicted"),
    aes(y = predicted, group = gid_1, color = source_type),
    linewidth = 1.5
  ) +
  geom_point(
    data = filter(df_togo, source_type != "Predicted"),
    aes(y = estimate, color = source_type, shape = source_type),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS" = "darkorange",
      "MICS" = "red",
      "LSMS" = "darkred",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS" = 16,
      "MICS" = 15,
      "LSMS" = 17
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Mobile Adoption (Women)",
    title = "Togo, Mobile Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = togo_plot, filename = here("figures", "togo_time_series_validation_mobile.png"), width = 12, heigh = 12) 
```

```{r}
## create combined dataframe 
df_tanzania <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="TZA", outcome=="internet_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) 

## Join on state names 
df_tanzania <- df_tanzania %>% 
  left_join(gadm1_map %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_tanzania <- df_tanzania %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS",
      TRUE ~ "Predicted"
    ))

## make plot 
tanzania_plot <- df_tanzania %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_tanzania),
    aes(y = predicted, group = gid_1, color = "Predicted"),
    linewidth = 1.5
  ) + 
  geom_point(
    data = filter(df_tanzania, source_type == "DHS"),
    aes(y = estimate, color = source_type, shape = source_type,),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS" = "darkorange",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS" = 16
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Internet Adoption (Women)",
    title = "Tanzania Internet Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = tanzania_plot, filename = here("figures", "tanzania_plot_time_series_validation_internet.png"), width = 12, heigh = 12) 
```


```{r}
## create combined dataframe 
df_tanzania <- predictions %>%
  group_by(year, gid_0, gid_1, outcome) %>% 
  summarize(
    predicted = mean(predicted, na.rm = TRUE),
    n = n()
  ) %>% 
  ungroup() %>% 
  left_join(estimates_long, by = c("gid_0", "gid_1", "year", "outcome")) %>%
  filter(gid_0=="TZA", outcome=="mobile_women") %>%
  mutate(date = as.Date(paste0(year, "-01-01"))) 

## Join on state names 
df_tanzania <- df_tanzania %>% 
  left_join(gadm1_map %>% as.data.frame() %>% select(gid_1 = GID_1, NAME_1)
) %>% 
  mutate(gid_1_name = paste0(NAME_1, " (", gid_1, ")")) %>% 
  mutate(NAME_1 = case_when(
    NAME_1 == "Federal Capital Territory" ~ "Capital Territory",
    TRUE ~ NAME_1
  )) %>% 
  mutate(survey_type = toupper(survey_type))

## create plot 
df_tanzania <- df_tanzania %>%
  mutate(
    source_type = case_when(
      survey_type == "DHS" ~ "DHS",
      TRUE ~ "Predicted"
    ))

## make plot 
tanzania_plot <- df_tanzania %>% 
  ggplot(aes(x = date)) +
  geom_line(
    data = filter(df_tanzania),
    aes(y = predicted, group = gid_1, color = "Predicted"),
    linewidth = 1.5
  ) + 
  geom_point(
    data = filter(df_tanzania, source_type == "DHS"),
    aes(y = estimate, color = source_type, shape = source_type,),
    size = 3, alpha = 1
  ) +
  scale_color_manual(
    values = c(
      "DHS" = "darkorange",
      "Predicted" = "lightblue"
    ),
    name = "Survey Source"
  ) +
  scale_shape_manual(
    values = c(
      "DHS" = 16
    ),
    name = "Survey Source"
  ) +
  guides(
    shape = "none",
    shape = guide_legend(order = 1)
  ) +
  facet_wrap(~NAME_1) +
  labs(
    x = "Year",
    y = "Mobile Adoption (Women)",
    title = "Tanzania Mobile Adoption (Women)"
  ) +
  theme_cowplot() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "white", color = "black", linewidth = 0.8),
    strip.text = element_text(size = 11, face = "bold"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    panel.background = element_rect(fill = "#f9f9f9"),
    panel.grid = element_line(color = "grey95"),
    panel.spacing = unit(1.5, "lines"),
    aspect.ratio = .9,
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  ) +
  ylim(0, 1)

## visualize plot 
ggsave(plot = tanzania_plot, filename = here("figures", "tanzania_plot_time_series_validation_mobile.png"), width = 12, heigh = 12) 
```


